### ISSUE TITLE
How do you extract data?

### ISSUE THREAD

**Issue by Cahllagerfeld** [NiHoel/Anno1404Calculator#1]
First of all nice work, you do a great job! 👍
My question is how do you extract the `params.js`?
You provide this file with all Gamedata for Anno 1800 and Anno 1404 as well.
Do you extract the data directly from the game and map them to a Js object, or how do you do that?

Many thank

Greets

Cahllagerfeld

**Comment by NiHoel** [comment]
Yes, I have a script to extract data from the game files.
Since extracting the game files is illegal, I won't discuss this in public.

If you want to know more about it, write me a mail (see help dialog of the calculator).
